In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [42]:
#/content/drive/MyDrive/Colab Notebooks/Covid.csv
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Covid.csv")
df.head(50)

,Nucleus,Exosome,Ribosome,Membrane,Endoplasmic Reticulum,Cytosol,Variant
0,0.999,1.000,0.720,0.840,0.450,0.000,Alpha
1,0.999,1.000,0.737,0.834,0.492,0.000,Alpha
2,0.999,1.000,0.729,0.831,0.497,0.000,Alpha
3,0.999,1.000,0.724,0.831,0.496,0.000,Alpha
4,0.999,1.000,0.644,0.818,0.271,0.000,Alpha
5,0.998,1.000,0.641,0.805,0.323,0.000,Alpha
6,0.999,1.000,0.725,0.846,0.422,0.000,Beta
7,0.999,1.000,0.722,0.847,0.432,0.000,Beta
8,0.999,1.000,0.717,0.842,0.448,0.000,Beta
9,0.999,1.000,0.729,0.845,0.442,0.000,Beta
10,0.999,1.000,0.729,0.843,0.455,0.000,Beta
11,0.999,1.000,0.722,0.840,0.467,0.000,Beta
12,0.999,1.000,0.715,0.841,0.455,0.000,Beta
13,0.803,0.998,0.000,0.389,0.000,0.000,Beta
14,0.955,1.000,0.000,0.623,0.248,0.000,Delta
15,0.948,1.000,0.000,0.676,0.240,0.000,Delta
16,0.954,1.000,0.000,0.621,0.249,0.000,Delta
17,0.980,1.000,0.000,0.759,0.000,0.000,Delta
18,0.980,1.000,0.000,0.759,0.000,0.000,Delta
19,0.980,1.000,0.000,0.759,0.000,0.000,Delta
20,0.979,1.000,0.000,0.765,0.000,0.000,Gamma
21,0.979,1.000,0.000,0.765,0.000,0.000,Gamma
22,0.978,1.000,0.000,0.764,0.000,0.000,Gamma
23,0.978,1.000,0.000,0.763,0.000,0.000,Gamma
24,0.978,1.000,0.000,0.762,0.000,0.000,Gamma
25,0.978,1.000,0.000,0.760,0.000,0.000,Gamma
26,0.977,1.000,0.000,0.758,0.000,0.000,Gamma
27,0.979,1.000,0.000,0.763,0.000,0.000,Gamma
28,0.977,1.000,0.000,0.758,0.000,0.000,Gamma
29,0.978,1.000,0.000,0.759,0.000,0.000,Gamma
30,0.978,1.000,0.000,0.762,0.000,0.000,Gamma
31,0.972,1.000,0.000,0.739,0.237,0.000,Omicron
32,0.949,1.000,0.000,0.730,0.000,0.000,Omicron
33,0.597,1.000,0.000,0.840,0.497,0.000,Alpha
34,0.998,1.000,0.729,0.817,0.387,0.000,Alpha
35,0.999,1.000,0.818,0.802,0.681,0.107,Alpha
36,0.895,0.996,0.000,0.355,0.346,0.088,Alpha
37,0.870,0.997,0.303,0.428,0.197,0.095,Beta
38,0.821,0.994,0.328,0.328,0.233,0.080,Beta
39,0.980,1.000,0.239,0.747,0.078,0.100,Beta
40,0.870,0.997,0.303,0.428,0.197,0.095,Beta
41,0.870,0.997,0.303,0.428,0.197,0.097,Beta
42,0.996,1.000,0.322,0.866,0.077,0.124,Beta
43,0.992,1.000,0.273,0.832,0.069,0.106,Beta
44,0.977,1.000,0.223,0.744,0.084,0.095,Beta
45,0.966,1.000,0.276,0.674,0.113,0.101,Beta
46,0.996,1.000,0.313,0.864,0.078,0.119,Beta

In [25]:
df.keys()

Index(['Nucleus', 'Exosome', 'Ribosome', 'Membrane', 'Endoplasmic Reticulum',
       'Cytosol', 'Variant'],
      dtype='object')

In [26]:
inputs = df.drop('Variant',axis='columns')
target = df.Variant

In [27]:
df.head()

,Nucleus,Exosome,Ribosome,Membrane,Endoplasmic Reticulum,Cytosol,Variant
0,0.999,1.0,0.720,0.840,0.450,0.0,Alpha
1,0.999,1.0,0.737,0.834,0.492,0.0,Alpha
2,0.999,1.0,0.729,0.831,0.497,0.0,Alpha
3,0.999,1.0,0.724,0.831,0.496,0.0,Alpha
4,0.999,1.0,0.644,0.818,0.271,0.0,Alpha

In [28]:
df.shape

(47, 7)

In [29]:
inputs.head()

   Nucleus  Exosome  Ribosome  Membrane  Endoplasmic Reticulum  Cytosol
0    0.999      1.0     0.720     0.840                  0.450      0.0
1    0.999      1.0     0.737     0.834                  0.492      0.0
2    0.999      1.0     0.729     0.831                  0.497      0.0
3    0.999      1.0     0.724     0.831                  0.496      0.0
4    0.999      1.0     0.644     0.818                  0.271      0.0

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2)

In [32]:
len(X_train)

37

In [33]:
len(X_test)

10

In [34]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [35]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [36]:
model.score(X_test,y_test)

0.7

In [37]:
df.corr()

,Nucleus,Exosome,Ribosome,Membrane,Endoplasmic Reticulum,Cytosol
Nucleus,1.000000,0.528646,0.325975,0.543831,-0.019297,-0.145317
Exosome,0.528646,1.000000,0.076637,0.880064,-0.012810,-0.443183
Ribosome,0.325975,0.076637,1.000000,0.361381,0.814965,0.043347
Membrane,0.543831,0.880064,0.361381,1.000000,0.201011,-0.360188
Endoplasmic Reticulum,-0.019297,-0.012810,0.814965,0.201011,1.000000,-0.051391
Cytosol,-0.145317,-0.443183,0.043347,-0.360188,-0.051391,1.000000

In [38]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier().fit(X_train, y_train)

print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 1.00
Accuracy of Decision Tree classifier on test set: 0.70

In [39]:
inputs.head()

   Nucleus  Exosome  Ribosome  Membrane  Endoplasmic Reticulum  Cytosol
0    0.999      1.0     0.720     0.840                  0.450      0.0
1    0.999      1.0     0.737     0.834                  0.492      0.0
2    0.999      1.0     0.729     0.831                  0.497      0.0
3    0.999      1.0     0.724     0.831                  0.496      0.0
4    0.999      1.0     0.644     0.818                  0.271      0.0

In [41]:
model.predict([[0.999,1,0.720,0.840,0.450,0.0]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"

array(['Alpha'], dtype=object)

In [43]:

model.predict([[0.980,1,0,0.759	,0,0]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"

array(['Delta'], dtype=object)

In [44]:
#From Random Dataset
model.predict([[0.962,1,0,0.645,0.239,0]]) 
#The input accurately predicted for >MH025764.1 Porcine deltacoronavirus strain CH/JXJGS01/P50, complete genome

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"

array(['Delta'], dtype=object)